Repository softeerbootcamp-2nd/android-slide, pull requests merged in 2023-07, with the labels that each got.

#1 [강현성] setup project
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/slideapp/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/slideapp/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/slideapp/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#7 [정혜린] Project SetUp
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/hr/slide_app/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hr/slide_app/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/hr/slide_app/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#9 [조예현] 프로젝트 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/slideapp/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/slideapp/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/slideapp/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#8 [박세영] 프로젝트 셋업
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/slide/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/slide/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/slide/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#6 [안승우] 프로젝트 세팅
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/io/softeer/slideapp/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/io/softeer/slideapp/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#12 [안승우] Slide 모델 만들기
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/softeer/slideapp/MainActivity.kt
  app/src/main/java/io/softeer/slideapp/data/RGBColor.kt
  app/src/main/java/io/softeer/slideapp/data/Size.kt
  app/src/main/java/io/softeer/slideapp/enum/SlideType.kt
  app/src/main/java/io/softeer/slideapp/factory/SlideFactory.kt
  app/src/main/java/io/softeer/slideapp/factory/TypeSlideFactory.kt
  app/src/main/java/io/softeer/slideapp/model/RectSlide.kt
  app/src/main/java/io/softeer/slideapp/model/Slide.kt
  app/src/main/res/layout-w600dp/activity_main.xml
  app/src/main/res/layout/activity_main.xml
Labels: step3-1

#14 [박세영] 슬라이드 앱 프로젝트
  README.md
  app/src/main/java/com/example/slide/MainActivity.kt
  app/src/main/java/com/example/slide/factory/ReactFactory.kt
  app/src/main/java/com/example/slide/model/React.kt
  app/src/main/java/com/example/slide/model/Slide.kt
  app/src/main/res/layout-w600dp/activity_main.xml
Labels: step3-1

#17 [조예현] 슬라이드 앱 프로젝트
  README.md
  app/src/main/java/com/example/slideapp/MainActivity.kt
  app/src/main/java/com/example/slideapp/Slide.kt
  app/src/main/java/com/example/slideapp/SlideItemFactory.kt
  app/src/main/java/com/example/slideapp/SquareSlideFactory.kt
Labels: step3-1

#20 [한병하] 프로젝트 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/glacier/androidslide/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/glacier/androidslide/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/glacier/androidslide/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#21 [한병하] 슬라이드 앱 프로젝트
  README.md
  app/src/main/java/com/glacier/androidslide/MainActivity.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlide.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlideFactory.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlideViewFactory.kt
  app/src/main/java/com/glacier/androidslide/util/UtilManager.kt
Labels: step3-1

#22 [안승우] 속성 변경 동작
  README.md
  app/build.gradle
  app/src/main/java/io/softeer/slideapp/MainActivity.kt
  app/src/main/java/io/softeer/slideapp/data/RGBColor.kt
  app/src/main/java/io/softeer/slideapp/data/Size.kt
  app/src/main/java/io/softeer/slideapp/factory/SlideFactory.kt
  app/src/main/java/io/softeer/slideapp/factory/TypeSlideFactory.kt
  app/src/main/java/io/softeer/slideapp/manager/SlideManager.kt
  app/src/main/java/io/softeer/slideapp/model/RectSlide.kt
  app/src/main/java/io/softeer/slideapp/model/Slide.kt
  app/src/main/java/io/softeer/slideapp/viewmodel/BindingAdapter.kt
  app/src/main/java/io/softeer/slideapp/viewmodel/SlideViewModel.kt
  app/src/main/res/drawable/tv_round_gray.xml
  app/src/main/res/drawable/tv_round_white.xml
  app/src/main/res/layout-w600dp/activity_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/io/softeer/slideapp/manager/SlideChangeAlphaTest.kt
  app/src/test/java/io/softeer/slideapp/manager/SlideChangeColorTest.kt
  app/src/test/java/io/softeer/slideapp/manager/SlideSelectTest.kt
Labels: step3-2

#40 [정혜린] Attribute Change / UDF
  README.md
  app/build.gradle
  app/src/main/java/com/hr/slide_app/Alpha.kt
  app/src/main/java/com/hr/slide_app/MainActivity.kt
  app/src/main/java/com/hr/slide_app/RGB.kt
  app/src/main/java/com/hr/slide_app/Slide.kt
  app/src/main/java/com/hr/slide_app/SlideFactory.kt
  app/src/main/java/com/hr/slide_app/SlideManager.kt
  app/src/main/java/com/hr/slide_app/SlideViewModel.kt
  app/src/main/java/com/hr/slide_app/Square.kt
  app/src/main/java/com/hr/slide_app/SquareSlideFactory.kt
  app/src/main/res/drawable/border.xml
  app/src/main/res/drawable/button.xml
  app/src/main/res/layout-sw600dp/activity_main.xml
  app/src/main/res/values/strings.xml
  step3-1_result.png
  step3-2,3_result.png
Labels: step3-2, step3-3

#32 [한병하] Unidirectional Data Flow 적용
  README.md
  app/build.gradle
  app/src/main/java/com/glacier/androidslide/MainActivity.kt
  app/src/main/java/com/glacier/androidslide/SlideManager.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlide.kt
  app/src/main/java/com/glacier/androidslide/viewmodel/SquareSlideViewModel.kt
  app/src/main/res/layout-sw600dp/activity_main.xml
  app/src/main/res/layout/activity_main.xml
Labels: step3-3

#27 [안승우] 단방향 데이터 흐름
  README.md
  app/build.gradle
  app/src/main/java/io/softeer/slideapp/data/RGBColor.kt
  app/src/main/java/io/softeer/slideapp/factory/SlideFactory.kt
  app/src/main/java/io/softeer/slideapp/manager/SlideManager.kt
  app/src/main/java/io/softeer/slideapp/viewmodel/SlideViewModel.kt
  app/src/main/res/layout-w600dp/activity_main.xml
  app/src/test/java/io/softeer/slideapp/manager/SlideChangeAlphaTest.kt
  app/src/test/java/io/softeer/slideapp/manager/SlideChangeColorTest.kt
Labels: step3-3

#39 [강현성] 슬라이드 목록 표시
  README.md
  app/build.gradle
  app/src/main/java/com/example/slideapp/adapter/SlideViewAdapter.kt
  app/src/main/java/com/example/slideapp/callback/ItemTouchHelperCallback.kt
  app/src/main/java/com/example/slideapp/listener/ItemTouchHelperListener.kt
  app/src/main/java/com/example/slideapp/models/SlideSquareView.kt
  app/src/main/java/com/example/slideapp/ui/MainActivity.kt
  app/src/main/java/com/example/slideapp/utils/combineColor.kt
  app/src/main/java/com/example/slideapp/utils/parseColor.kt
  app/src/main/java/com/example/slideapp/view/CustomSquareView.kt
  app/src/main/java/com/example/slideapp/viewmodels/SlideManagerViewModel.kt
  app/src/main/res/drawable/btn_add_slide.xml
  app/src/main/res/drawable/ic_file.png
  app/src/main/res/drawable/ic_gallery.png
  app/src/main/res/drawable/v_slide_background.xml
  app/src/main/res/drawable/v_slide_background2.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/adapter_slide_photo_item.xml
  app/src/main/res/layout/adapter_slide_square_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: step3-4

#50 [강현성] step-3 사진 슬라이드 추가하기
  README.md
  app/build.gradle
  app/src/main/java/com/example/slideapp/adapter/SlideViewAdapter.kt
  app/src/main/java/com/example/slideapp/callback/ItemTouchHelperCallback.kt
  app/src/main/java/com/example/slideapp/listener/ItemClickListener.kt
  app/src/main/java/com/example/slideapp/listener/ItemLongClickListener.kt
  app/src/main/java/com/example/slideapp/listener/doubleTapListener.kt
  app/src/main/java/com/example/slideapp/listener/singleTapListener.kt
  app/src/main/java/com/example/slideapp/models/Color.kt
  app/src/main/java/com/example/slideapp/models/Photo.kt
  app/src/main/java/com/example/slideapp/models/SlideSquareView.kt
  app/src/main/java/com/example/slideapp/models/Square.kt
  app/src/main/java/com/example/slideapp/ui/MainActivity.kt
  app/src/main/java/com/example/slideapp/utils/bindingAdapter.kt
  app/src/main/java/com/example/slideapp/utils/combineColor.kt
  app/src/main/java/com/example/slideapp/view/CustomSquareView.kt
  app/src/main/java/com/example/slideapp/viewmodels/SlideManagerViewModel.kt
  app/src/main/res/drawable/steve.jpeg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/adapter_slide_photo_item.xml
  app/src/main/res/layout/adapter_slide_square_item.xml
  app/src/main/res/layout/adapter_slide_view_item.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/strings.xml
Labels: step3-5

#55 [조예현] 사진 슬라이드 추가하기
  README.md
  app/build.gradle
  app/src/main/java/com/example/slideapp/ARGB.kt
  app/src/main/java/com/example/slideapp/Alpha.kt
  app/src/main/java/com/example/slideapp/MainActivity.kt
  app/src/main/java/com/example/slideapp/Slide.kt
  app/src/main/java/com/example/slideapp/SlideListAdapter.kt
  app/src/main/java/com/example/slideapp/SlideManager.kt
  app/src/main/java/com/example/slideapp/SlideViewModel.kt
  app/src/main/res/drawable/baseline_image_search_24.xml
  app/src/main/res/layout-sw600dp/activity_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_option.xml
Labels: step3-5

#53 [한병하] 서버에서 슬라이드 불러오기
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/glacier/androidslide/MainActivity.kt
  app/src/main/java/com/glacier/androidslide/SlideManager.kt
  app/src/main/java/com/glacier/androidslide/adapter/SlideAdapter.kt
  app/src/main/java/com/glacier/androidslide/api/JsonSlideApi.kt
  app/src/main/java/com/glacier/androidslide/api/JsonSlideDeserializer.kt
  app/src/main/java/com/glacier/androidslide/api/RetrofitInstance.kt
  app/src/main/java/com/glacier/androidslide/model/ImageSlide.kt
  app/src/main/java/com/glacier/androidslide/model/JsonSlides.kt
  app/src/main/java/com/glacier/androidslide/model/Slide.kt
  app/src/main/java/com/glacier/androidslide/model/SlideColor.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlide.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlideFactory.kt
  app/src/main/java/com/glacier/androidslide/model/SquareSlideViewFactory.kt
  app/src/main/java/com/glacier/androidslide/viewmodel/MainViewModel.kt
Labels: step4-1
